// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody": {
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_kunduk1_manage-task-service_pkg_auth_v1.LoginRequest": {
                "properties": {
                    "email": {
                        "example": "user@example.com",
                        "type": "string"
                    },
                    "password": {
                        "example": "s3cret-pass",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_kunduk1_manage-task-service_pkg_auth_v1.LoginResponse": {
                "properties": {
                    "access_token": {
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                        "type": "string"
                    },
                    "expires_in": {
                        "example": 900,
                        "type": "integer"
                    },
                    "refresh_token": {
                        "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                        "type": "string"
                    },
                    "token_type": {
                        "example": "Bearer",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_kunduk1_manage-task-service_pkg_auth_v1.RegisterRequest": {
                "properties": {
                    "email": {
                        "example": "user@example.com",
                        "type": "string"
                    },
                    "name": {
                        "example": "Jane Doe",
                        "type": "string"
                    },
                    "password": {
                        "example": "s3cret-pass",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "github_com_kunduk1_manage-task-service_pkg_auth_v1.RegisterResponse": {
                "properties": {
                    "email": {
                        "example": "user@example.com",
                        "type": "string"
                    },
                    "id": {
                        "example": 42,
                        "type": "integer"
                    },
                    "name": {
                        "example": "Jane Doe",
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/login": {
            "post": {
                "description": "Validates credentials and returns access/refresh tokens.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_pkg_auth_v1.LoginRequest",
                                        "summary": "request",
                                        "description": "login payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "login payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_pkg_auth_v1.LoginResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Log in and obtain tokens",
                "tags": [
                    "auth"
                ]
            }
        },
        "/register": {
            "post": {
                "description": "Creates a user account and returns its public profile.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_pkg_auth_v1.RegisterRequest",
                                        "summary": "request",
                                        "description": "registration payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "registration payload",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_pkg_auth_v1.RegisterResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Conflict"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_kunduk1_manage-task-service_internal_transport_response.ErrorBody"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Register a new user",
                "tags": [
                    "auth"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "http://localhost:8080/api/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Manage Task Service API",
	Description:      "Auth/tasks/teams API for manage-task-service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
