package docs

import _ "embed"

// SwaggerJSON holds the generated OpenAPI 3.1 spec, embedded so the HTTP layer
// can serve it directly. http-swagger/v2 reads from the swag v1 registry while
// `swag init` (v2) registers into the v2 registry, so we bypass that mismatch
// and serve the spec ourselves. Regenerated by `make swagger`.
//
//go:embed swagger.json
var SwaggerJSON []byte
